swagger: "2.0"
info:
  title: CloudWatch API Lab
  version: "1.0"

schemes:
  - https

paths:

  /hello:
    get:
      produces:
        - application/json
      x-amazon-apigateway-integration:
        type: AWS_PROXY
        httpMethod: POST
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloLambdaArn}/invocations
      responses:
        "200":
          description: OK

  /error:
    get:
      produces:
        - application/json
      x-amazon-apigateway-integration:
        type: AWS_PROXY
        httpMethod: POST
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloLambdaArn}/invocations
      responses:
        "500":
          description: Internal Server Error
