swagger: "2.0"

info:
  title: CloudWatch API Gateway Lab
  version: "1.0"

schemes:
  - https

paths:

  /hello:
    get:
      produces:
        - application/json
      responses:
        "200":
          description: Successful response

  /error:
    get:
      produces:
        - application/json
      responses:
        "500":
          description: Simulated server error

  /test:
    get:
      produces:
        - application/json
      responses:
        "200":
          description: Successful response
